export const BUSINESS_TYPES = [
    {
        id: "vshe_neft",
        name: "ВШЭнефть",
        icon: "🛢️",
        basePrice: 1200000,
        marketType: "monopoly",
        demandA: 60,
        demandB: 1,
        costA: 2,
        costB: 6,
        costC: 0,
        description: "Нефтедобывающая компания. Работает как монополист на рынке.",
        minPrice: 1,
        maxPrice: 60
    },
    {
        id: "vshe_stroy",
        name: "ВШЭстрой",
        icon: "🏗️",
        basePrice: 500000,
        marketType: "perfect_competition",
        competitors: 15,
        demandA: 100,
        demandB: 1,
        costA: 0,
        costB: 10,
        costC: 1,
        description: "Строительная компания. Работает в условиях совершенной конкуренции.",
        minPrice: 10,
        maxPrice: 100
    },
    {
        id: "vshe_sklad",
        name: "ВШЭсклад",
        icon: "📦",
        basePrice: 400000,
        marketType: "perfect_competition",
        competitors: 12,
        demandA: 80,
        demandB: 1,
        costA: 1,
        costB: 7,
        costC: 80,
        description: "Складской комплекс. Услуги хранения в условиях высокой конкуренции.",
        minPrice: 8,
        maxPrice: 80
    },
    {
        id: "vshe_magazin",
        name: "ВШЭМагазин",
        icon: "🛒",
        basePrice: 600000,
        marketType: "stackelberg_follower",
        competitors: 1,
        demandA: 50,
        demandB: 1,
        costA: 0,
        costB: 8,
        costC: 0,
        competitorCostA: 0,
        competitorCostB: 6,
        competitorCostC: 0,
        description: "Сеть магазинов. Работает в модели олигополии Штакельберга. Ваша фирма – последователь",
        minPrice: 1,
        maxPrice: 50
    },
    {
        id: "vshe_line",
        name: "ВШЭЛайн",
        icon: "📱",
        basePrice: 750000,
        marketType: "cournot",
        competitors: 1,
        demandA: 100,
        demandB: 1,
        costA: 2,
        costB: 4,
        costC: 0,
        competitorCostA: 1,
        competitorCostB: 4,
        competitorCostC: 0,
        description: "Мобильный оператор. Работает в модели олигополии Курно.",
        minPrice: 4,
        maxPrice: 100
    },
    {
        id: "vshe_taxi",
        name: "ВШЭТакси",
        icon: "🚕",
        basePrice: 800000,
        marketType: "monopoly",
        demandA: 90,
        demandB: 2,
        costA: 1,
        costB: 12,
        costC: 0,
        description: "Таксомоторная служба. Монополия в городе благодаря эксклюзивной лицензии.",
        minPrice: 6,
        maxPrice: 90
    }
];
