export const BUSINESS_TYPES = [
    {
        id: "vshe_neft",
        name: "ВШЭнефть",
        icon: "🛢️",
        basePrice: 3000000,
        marketType: "monopoly",
        demandA: 10,
        demandB: 1,
        costA: 1,
        costB: 0,
        costC: 0,
        description: "Нефтедобывающая компания. Работает как монополист на рынке.",
        minPrice: 1,
        maxPrice: 10
    },
    {
        id: "vshe_stroy",
        name: "ВШЭстрой",
        icon: "🏗️",
        basePrice: 500000,
        marketType: "perfect_competition",
        competitors: 15,
        demandA: 100,
        demandB: 1,
        costA: 0,
        costB: 10,
        costC: 0,
        description: "Строительная компания. Работает в условиях совершенной конкуренции.",
        minPrice: 10,
        maxPrice: 90
    },
    {
        id: "vshe_sklad",
        name: "ВШЭсклад",
        icon: "📦",
        basePrice: 400000,
        marketType: "perfect_competition",
        competitors: 12,
        demandA: 80,
        demandB: 1,
        costA: 0,
        costB: 8,
        costC: 100,
        description: "Складской комплекс. Услуги хранения в условиях высокой конкуренции.",
        minPrice: 8,
        maxPrice: 72
    },
    {
        id: "vshe_magazin",
        name: "ВШЭМагазин",
        icon: "🛒",
        basePrice: 600000,
        marketType: "stackelberg_leader",
        competitors: 1,
        demandA: 30,
        demandB: 1,
        costA: 0,
        costB: 15,
        costC: 0,
        competitorCostB: 10,
        competitorCostC: 0,
        description: "Сеть магазинов. Работает в модели олигополии Штакельберга.",
        minPrice: 1,
        maxPrice: 29
    },
    {
        id: "vshe_line",
        name: "ВШЭЛайн",
        icon: "📱",
        basePrice: 700000,
        marketType: "cournot",
        competitors: 1,
        demandA: 100,
        demandB: 1,
        costA: 2,
        costB: 0,
        costC: 0,
        competitorCostA: 1,
        competitorCostB: 0,
        competitorCostC: 0,
        description: "Мобильный оператор. Работает в модели олигополии Курно.",
        minPrice: 1,
        maxPrice: 99
    },
    {
        id: "vshe_taxi",
        name: "ВШЭТакси",
        icon: "🚕",
        basePrice: 800000,
        marketType: "monopoly",
        demandA: 150,
        demandB: 3,
        costA: 2,
        costB: 30,
        costC: 200,
        description: "Таксомоторная служба. Монополия в городе благодаря эксклюзивной лицензии.",
        minPrice: 5,
        maxPrice: 145
    }
];
